"""add video history table

Revision ID: 6ef545e0e95d
Revises: a07144c0dbb0
Create Date: 2026-02-26 02:57:08.537895

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6ef545e0e95d"
down_revision = "a07144c0dbb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_history")
    # ### end Alembic commands ###
